services:
  postgres:
    image: postgres:16-alpine
    container_name: pb-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/pg_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10M

  eureka:
    image: cr.yandex/crpop0r0f81mcsvg9kei/port-buddy-eureka:latest
    container_name: pb-eureka
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${PWD}/eureka/config:/app/config
      - ${PWD}/eureka/logs:/app/logs
    logging:
      options:
        max-size: 10M

  server:
    image: cr.yandex/crpop0r0f81mcsvg9kei/port-buddy-server:latest
    container_name: pb-server
    restart: unless-stopped
    network_mode: host
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PRICE_PRO: ${STRIPE_PRICE_PRO}
      STRIPE_PRICE_TEAM: ${STRIPE_PRICE_TEAM}
      STRIPE_PRICE_EXTRA_TUNNEL: ${STRIPE_PRICE_EXTRA_TUNNEL}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      OAUTH_GOOGLE_CLIENT_ID: ${OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_GITHUB_CLIENT_ID: ${OAUTH_GITHUB_CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET: ${OAUTH_GITHUB_CLIENT_SECRET}
    volumes:
      - ${PWD}/server/config:/app/config
      - ${PWD}/server/logs:/app/logs
    depends_on:
      - eureka
      - postgres
    logging:
      options:
        max-size: 100M

  gateway:
    image: cr.yandex/crpop0r0f81mcsvg9kei/port-buddy-gateway:latest
    container_name: pb-gateway
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${PWD}/gateway/config:/app/config
      - ${PWD}/gateway/logs:/app/logs
    depends_on:
      - eureka
    logging:
      options:
        max-size: 10M

  net-proxy:
    image: cr.yandex/crpop0r0f81mcsvg9kei/port-buddy-net-proxy:latest
    container_name: pb-net-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${PWD}/net-proxy/config:/app/config
      - ${PWD}/net-proxy/logs:/app/logs
    depends_on:
      - eureka
    logging:
      options:
        max-size: 10M

  ssl-service:
    image: cr.yandex/crpop0r0f81mcsvg9kei/port-buddy-ssl-service:latest
    container_name: pb-ssl-service
    restart: unless-stopped
    network_mode: host
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${PWD}/ssl-service/config:/app/config
      - ${PWD}/ssl-service/logs:/app/logs
      - ${PWD}/ssl-service/certs:/app/certs
    depends_on:
      - eureka
      - postgres
    logging:
      options:
        max-size: 10M
