server:
  port: 8090
  compression:
    enabled: on

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  gateway:
    domain: localhost:8080
    schema: http
    url: ${app.gateway.schema}://${app.gateway.domain}
  mail:
    fromAddress: ${MAIL_FROM:no-reply@portbuddy.dev}
    fromName: ${MAIL_FROM_NAME:Port Buddy}

  tunnels:
    heartbeat-timeout: 2m
    check-interval: 30s

  jwt:
    issuer: port-buddy
    ttl: 168h # 1 week
    rsa:
      currentKeyId: dev-key
      keys:
        - id: dev-key
          publicKeyPem: ${PUBLIC_KEY:classpath:keys/dev_jwt.pub}
          privateKeyPem: ${PRIVATE_KEY:classpath:keys/dev_jwt.pem}

  web-socket:
    max-text-message-size: 100MB
    max-binary-message-size: 1GB
    session-idle-timeout: 10m

spring:
  mvc:
    problem-details:
      enabled: true
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB

  application:
    name: port-buddy-server
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:portbuddy}
    username: ${DB_USER:portbuddy}
    password: ${DB_PASSWORD:portbuddy}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 943200305645-kk9e9767lc9andmtlhamht42gjaguriq.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: "${app.gateway.url}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  mail:
    host: ${SMTP_HOST:postbox.cloud.yandex.net}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        mime:
          charset: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info
    tech.amak.portbuddy: debug
    org.springframework.web: info
  file:
    name: log/app.log
  logback:
    rollingpolicy:
      max-history: 14
      total-size-cap: 1000MB
      max-file-size: 100MB
