server:
  port: 8090
  compression:
    enabled: on

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  gateway:
    domain: localhost:8080
    schema: http
    url: ${app.gateway.schema}://${app.gateway.domain}

  tunnels:
    heartbeat-timeout: 2m
    check-interval: 30s

  jwt:
    issuer: port-buddy
    ttl: 168h # 1 week
    rsa:
      currentKeyId: dev-key
      keys:
        - id: dev-key
          publicKeyPem: ${PUBLIC_KEY:classpath:keys/dev_jwt.pub}
          privateKeyPem: ${PRIVATE_KEY:classpath:keys/dev_jwt.pem}

  web-socket:
    max-text-message-size: 100MB
    max-binary-message-size: 1GB
    session-idle-timeout: 10m

spring:
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB

  application:
    name: port-buddy-server
  datasource:
    url: jdbc:postgresql://localhost:5432/port_buddy
    username: port_buddy
    password: port_buddy
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 943200305645-kk9e9767lc9andmtlhamht42gjaguriq.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: "${app.gateway.url}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info
    tech.amak.portbuddy: debug
    org.springframework.web: debug